< ../config.mk

MKSHELL=/bin/bash

all:VQ:
	set -x
	bin/targets | xargs mk 


results/%.pdf: data/doi.txt
	set -x
	mkdir -p `dirname $target`
	while read DOI
	do
		echo "descargando $BASEURL2$DOI"
		DOWNLOAD_URL=$(wget -q -O - $BASE_URL2$DOI | grep 'onclick' | cut -d "'" -f2)
		echo "descargando desde $DOWNLOAD_URL"
		wget -O results/$(echo $DOI | tr "/" "_" )pdf.build $DOWNLOAD_URL \
		&& mv results/$(echo $DOI | tr "/" "_" )pdf.build results/$(echo $DOI | tr "/" "_" )pdf
	done < <(cat $prereq)

data/doi.txt:
	set -x
	mkdir -p `dirname $target`
	cut -f3 data/prueba.tsv | grep -v "DOI" > $target.build \
	&& mv $target.build $target
