< ../config.mk
all:VQ:
	set -x
	bin/targets | xargs mk 


results/%/paper.pdf: data/doi.txt
	mkdir -p `dirname $target`
	wget -q -O  $BASE_URL2$prereq \
	| xargs grep 'onclick' \
	| cut -d "'" -f2 \
	| xargs wget > $target.build \
	&& mv $target.build $target
